name: 'repo'

on:
  repository_dispatch:
    types: 
      - package_update
  workflow_dispatch:
    inputs:
      repository:
        description: 'where to look for a release'
        required: true
      release: 
        description: 'release to download'
        required: true
      branch:
        description: 'manjaro lifecycle branch'
        required: true
        type: choice
        options:
        - stable
        - testing
        - unstable

env:
  repository: ${{ github.event.client_payload.repository || inputs.repository }}
  release: ${{ github.event.client_payload.release || inputs.release }}
  branch: ${{ github.event.client_payload.branch || inputs.branch }}

concurrency:
  ## fallbacks only needed for push-events
  group: ${{ github.event.client_payload.repository || inputs.repository }}-${{ github.event.client_payload.branch || inputs.branch }}
  cancel-in-progress: true

jobs:
  repo-add:
    ## fallbacks only needed for push-events
    name: add  ${{ github.event.client_payload.repository || inputs.repository }}@${{ github.event.client_payload.release || inputs.release }} to ${{ github.event.client_payload.branch || inputs.branch }}
    runs-on: ubuntu-latest
    container: docker://archlinux:base
    permissions:
      contents: write
    steps:
      - name: install tools
        shell: bash
        run: |
          pacman -Sy --noconfirm --needed git git-lfs github-cli
      - id: repo-add
        uses: manjaro-contrib/action-repo-add@main
        with:
          repository: ${{ env.repository }}
          release: ${{ env.release }}
          branch: ${{ env.branch }}
          gpg_keyid: ${{ vars.gpg_keyid }}
          gpg_secret_base64: ${{ secrets.gpg_secret_base64 }}
  publish:
    runs-on: ubuntu-latest
    needs: [repo-add]
    permissions:
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          fetch-depth: 1
          lfs: true
          ref: ${{ github.event.repository.default_branch }}
      - name: setup pages
        uses: actions/configure-pages@v3
      - name: copy gpg_keyid into place
        run: |
          mkdir -p docs/_includes
          echo ${{ vars.gpg_keyid }} >docs/_includes/keyid.asc
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v1
      - name: deploy pages
        uses: actions/deploy-pages@v1
